cheshire-cat-ai/plugins

- plugins.json
Cheshire Cat "Feed the Cat" Plugin is an experimental tool that allows you to manage your RSS feeds easily and efficiently. With this plugin, you can:
- Add RSS feeds to a list of feeds saved in a CSV file
- Remove RSS feeds from a list of feeds saved in a CSV file
- Show the list of RSS feeds
- Get the links to the most up-to-date news, based on the date of last query
> Added Feed the Cat plugin

- plugins.json
CCBooks is a plugin developed for Cheshire Cat AI designed to simplify the search for book information through the exclusive use of the ISBN.
This tool integrates seamlessly into the Cheshire Cat environment offering users a quick and efficient way to access vital details about books .
With CCBooks simply enter the ISBN number of the desired book and let the plugin take care of the rest.
Using the Google API crucial details such as author title publisher publication datedescription small image and many others are retrieved.
This information is presented in a clear and organized manner allowing users to quickly get a complete overview of the book they are interested in and can interact with specific questions.
> Add my plugins CCbooks

- plugins.json
Adding new 3 plugins:
- MistralAI, Adding support of the SaaS service they offer. Similar price of OpenAI
- OllamaFix, A Runtime fix for ollama class to be able to use the automatic stop string list from the runner
- Jina Embedders, Requested by @nickprock
> MistralAI support,Ollama runtime Fix and jina embedder support

- plugins.json
https://github.com/pazoff/PDF-to-Audio-Plugin
PDF to Audio Cat plugin for your [Cheshire cat](https://github.com/cheshire-cat-ai/core) involves converting text content in PDF files into audio (MP3,OGG,WAV), enabling you to listen to the document instead of reading it.
> add PDF to Audio Cat plugin

- plugins.json
https://github.com/pazoff/wolfram-alpha-cat
Connects the Cheshire Cat to the Wolfram Alpha using its free API.
> add Wolfram Alpha Cat plugin

- plugins.json
This plugin allows to use Hugging Face Embedder API Endpoint for sentence-embeddings
> Add Hugging Face Embedder Endpoint endpoint

- plugins.json
Purrfectly Clear Background is a simple plugin that lets you remove the background from an image you upload in chat
> Add the image background remover plugin

- plugins.json
Youtube 2 Text is a plugin that automatically transcribes the content of YouTube videos. It operates simply put a link to the video and the desired language code into the [Cheshire Cat AI](https://github.com/cheshire-cat-ai) conversational form.
> Add Youtube 2 text plugin

- plugins.json
This is a plugin that let your customers book an appointment directly in the chat!
This plugin is thought as an add-on for a B2C chatbot, for example it can be used in a chatbot on a website of accountants to book consultancies. An interesting feature is that it extracts the context of the chat previous the booking phase and give the booking a title (in the plugin called context).
> Add CatLendar plugin

- plugins.json
CATalogator is a plugin for Cheshire-Cat that allows users to assign metadata to documents during upload and apply filters to the declarative memory to focus responses on specific documents.
Rif: https://github.com/cheshire-cat-ai/core/issues/812
> Added CATalogator plugin

- plugins.json
**This plugin:**
1. classify your documents with metadata
2. filter your documents filters by metadata.
**How it works???**
1. 1. Concatenates a parameterizable number of chunks (set the number in settings)
2. Reads the possible metadata in list_of_tags.json (You could edit the list depending on your documentation, Do not cancel "no classification" from the list)
3. Evaluates what is the correct metadata for each chunk analizing the concatenated content and classifies it using the list in list_of_tags.json
4. Upload each chunk that composes the concatenated content with the discoreved metadada
5. If the cat cannot find the correct metadata, generates a possible metadata of the chunk (set the prompt and/or disable this function from settings)
6. Before recalling declarative memory analyses …
> Auto metadata chunk and filter

- plugins.json
**AWS Client Configuration Manager**:
This plugin, available at [AWS Client Configuration Manager](https://github.com/ggiallo28/aws-integration), is designed to integrate the Cat with AWS Cloud. It handles authentication by dynamically selecting credentials from the user's configuration with the following priority:
- AWS IAM Role
- AWS Credential Profile
- AWS Access Key (AK) and Secret Key (SK)
**Amazon Bedrock Embedders**:
The [Amazon Bedrock Embedders](https://github.com/ggiallo28/amazon-bedrock-embedders) plugin integrates Amazon Bedrock Embedders with the Cat. It utilizes the AWS Integration Plugin to manage AWS IAM-based authentication.
**Amazon Bedrock LLMs**:
This plugin, available at [Amazon Bedrock LLMs](https://github.com/ggiallo28/amazon-bedrock-llms), integrates Amazon …
> Add Amazon Bedrock Plugins

- plugins.json
This is a plugin that when the Cat starts saves a zipped copy of the 'data' folder in './cat/static/backup/' that can be recovered if necessary. To force another save just write:: ...save the cat's data.
> Add My Cat Data Backup plugin

- plugins.json
Create and handle groups using this plugin. CCat Groups enables the segmentation of declarative memory based on group names. The group admin can add users and upload documents to Rabbit Hole. Every group member will retrieve these documents to augment the prompt.
example:
1. User `admin` creates a group called `test` and switches the current group to test by using  `@p test`
2. `admin` uploads documents to Rabbit Hole.
3. `admin` adds the user `pippo` to `test`
4. `pippo` can use command `@l` to get the groups' list, that includes the group `test`
5. `pippo` can switch his active group to `test` by using command: `@p test`
6. ⁠When ⁠ `pippo` ⁠ makes a query about something, the retrieval phase includes all the documents previously uploaded by the admin belonging to the group `test`
> Add Ccat Groups plugin

- plugins.json
This plugin will help Cheshire cat users by assisting them in ingesting repository source code, documentation sites and questions for a specific library
In the current release, you can:
- import a GitHub repository with or without a GitHub API token (`@getcode library_name`)
- search and ingest a page from a site (useful if you want to import existing documentation (`@getcodedoc URL`)
planned features:
- search with Google for additional pages
- search in StackOverflow for a topic
> add Cat Overflow plugin

- plugins.json
This plugin features a tool and a hook.
The tool simply use 2 APIs the get detailed info about a card and the hook set a proper prompt to the chain.
> my plugin to leverage Scryfall public API the get info about MTG cards

- plugins.json
Plugin that allow the cat to generate different file types: at the moment, txt and pdf files are supported
> Add Cat File Generator plugin to plugins.json

- plugins.json
This plugin helps in removing useless and annoying header and footer lines in the documents before the chunking happens. The header and footer are inferred by looking for the same lines in the top of bottom of multiple pages.  The comparison is done with fuzzy similarity to avoid small differences as page numbers to ruin the process.
> Header and Footer CATter plugin to plugins.json

- plugins.json
No Think Plugin for The Cat (Qwen3)
This plugin helps:
Prepend /no_think to incoming messages (Qwen3)
Strip /no_think before storing in memory or recalling (Qwen3)
Remove internal thinking blocks <think> Thinking: ... Result (like Thinking: ... Result:) from the final output sent to the user (all R models)
> Update plugins.json No Think Plugin for The Cat (Qwen3)

- plugins.json
Hi folks, this is my first official submission, so be patient!
This is a plugin for Cheshire Cat AI that provides direct access to declarative memory without LLM overhead.
It could be used to help integration with third parties solutions that may be difficult to integrate natively within the CAT.
For instance it could be used to retrieve declarative memory to be used as context for external LLMs or closed systems.
The plugin includes a `plugin.json` and a `README.md` in its repository.
https://github.com/mc9625/mem_retriever
Here is the .zip release: https://github.com/mc9625/mem_retriever/archive/refs/tags/v0.1.0.zip
Thank you for your patience, your support and your great job!
> Add Declarative-memory-api-plugin to registry
