cheshire-cat-ai/plugins

plugins.json
This plugin is gonna smash you all, amateurs !!111!!!!1!!
=> Submit Meow Todo List

README.md, plugins.json
- Add the best plugin in business e the list
- Fix `readme.md` JSON examples
=> Add PurrCast plugin and correct readme example

plugins.json
Here a new plugin to prevent multiple file ingestion
=> Add Dietician

plugins.json
Search the internet using Google and get a list of web pages with titles, descriptions, and links.
=> Add CuriousCat plugin

plugins.json
This plugin is able to communicate with Mikrotik router using http rest API ([reference](https://help.mikrotik.com/docs/display/ROS/REST+API)).
It is able to get info about the router and interfaces.
The short-time program for the future is to perform query about interface speed or connected devices. Mikrotik APIs have write access too, so it will be also possible to edit the router configuration.
=> + Added mikrotik plugin

plugins.json
Add My plugin wonderland weather
=> Add My plugin wonderland weather

plugins.json
added plugin Cheshire Cat Prompt Settings
=> Cheshire Cat Prompt Settings

plugins.json
added Gerry Scatty.
Gerry Scatty ask question in trivial style.
=> updated plugins.json

plugins.json
Reranker based on Lost In [The Middle paper](https://arxiv.org/abs/2307.03172).
It reorder the list of documents returned by the retriever for the declarative memory
=> added lost in the middle

plugins.json
the ownership is changed from nickprock to Furrmidable-Crew
=> changed url

plugins.json
This plugin allows the cheshire cat to retrieve up-to-date football data.
=> Add Cheshire Football Data

plugins.json
This simple yet powerful Cheshire Cat AI plugin, known as the 'MadHatter Security Assistant,' is not just an ordinary addition to your cybersecurity toolkit—it's a virtual guardian with a whimsical touch. This eccentric assistant possesses an array of capabilities aimed at enhancing cybersecurity awareness and providing invaluable guidance to users navigating the intricate landscape of online security.
Additionally, this virtual assistant excels in educating users about the ever-evolving cyber threats. It provides not only timely alerts but also detailed explanations, making cybersecurity concepts accessible to users of all levels of expertise. Its interactive nature engages users in a dialogue, ensuring that the learning process is both informative and enjoyable.
Furthermore, the …
=> Add Mad Hatter Security Assistant

plugins.json
=> Add Cheshire Cat Reranker

plugins.json
Ask for a fact to the Cheshire Cat, it will give it back to you in ascii style (using `cowsay`). 
To use it, you need a free `api_key` from [here](api-ninjas.com)
=> add: the catscii artist plugin

plugins.json
Catnip Is a plugin for receive good news!
=> add Catnip to plugins!

plugins.json
=> Add GLaDOS plugin

plugins.json
I have added my plugins:
- cat-puppy: The cat has a puppy that sometimes answers for him... but it's a baby llama
- cat-form: the cat knows how to collect the data you need in a conversational way!
=> Maxdam plugins

plugins.json
[![awesome plugin](https://custom-icon-badges.demolab.com/static/v1?label=&message=awesome+plugin&color=383938&style=for-the-badge&logo=cheshire_cat_ai)](https://)  
A plugin that makes possible the [Cheshire Cat](https://github.com/cheshire-cat-ai) to be able to speak.
- **Mimic 3:** [Documentation](https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mimic-tts/mimic-3)
1. Download the files
2. Extract the archive to the Plugins folder of your cheshire cat installation
3. Enable the plugin from the Plugins menu of the cheshire cat dashboard
GPL License
=> Add Mycroft Cat Plugin

plugins.json
I have 2 outdated plugins (cc_swith_user_role and cc_miltilingual) there are not updated because there are obsoletes with latest cat features. Please remove from plugin repos
=> Remove my outdated plugins

plugins.json
Supercharge your Meowgram client with the Meowgram Connect plugin, enabling smooth integration with the Cheshire Cat framework.
=> Added Meowgram Connect

plugins.json
https://github.com/pazoff/Stable-Diffusion-Cat
Generate images using your Cheshire cat and Stable Diffusion free API (Wizmodel.com API).
=> Add Stable Diffusion Cat plugin

plugins.json
Adding Fireworks-integration plugin, a SaaS Service for open models
=> Add Fireworks-integration

plugins.json
https://github.com/pazoff/Bing-Image-Creator-Cat 
Generate images for free using your [Cheshire cat](https://github.com/cheshire-cat-ai/core) and [Bing Image Creator](https://www.bing.com/images/create).
=> add Bing Image Creator Cat plugin

plugins.json
Add SBERT Integration
https://github.com/nickprock/sbert-integration
This plugin allows you to use sentence transformer models.
=> Add SBERT Integration

plugins.json
Finally they understand how a SaaS should work... No more prompt template
=> TogetherAI Integration

plugins.json
=> Add plugin Scrapycat and Url content in prompt

plugins.json
https://github.com/pazoff/Games-Cat
This plugin brings games to the Cheshire Cat framework.
=> add Games Cat plugin

plugins.json
The plugin allows you to talk to the Cheshire Cat or to the Caterpillar, who really wants to know 'Who are you?' 
It allows you to provide details about your identity and preferences in the settings. 
You can specify:
1. First name
2. Last name
3. Date of birth
4. Country
5. Preferred Language
6. Hobbies and interest
7. Anything relevant to know: here you can put all the information that you want the Cat or the Caterpillar take into account while having a conversation with you. 
The Cat/Caterpillar can wish you happy birthday, compute your age and answer to what day or time it is today.
=> added plugin who are you (user identity and preferences)

plugins.json
https://github.com/pazoff/GroqAI-Integration
Integration of GroqAI for the Cheshire cat framework - GroqAI - the fastest inference in the world.
=> add GroqAI Integration plugin and Ollama Embeddings Integration

plugins.json
https://github.com/vverrastro/cat-suggestions
Cat Suggestions Plugin enhances the conversational experience by providing users with contextually appropriate suggestions for continuing the conversation with the assistant.
**Features**
- Contextual Suggestions: The plugin analyzes the conversation's context in real-time and generates suggestions that are relevant to the topic being discussed.
- Dynamic Interaction: It adapts to the changing flow of the conversation, ensuring that the suggestions remain pertinent as the discussion evolves.
=> Add Cat Suggestions Plugin

plugins.json
This plugin adds a configuration to LLMs to use anthropic api, like claude 3.
=> Add the Claude AI plugin in plugins.json

plugins.json
This plugin permit to segment DOC, DOCX documents in the rabbithole.
=> add purrfectdocs

plugins.json
This plugin implements a custom parser that allows to recursively scrape all the URLs in a given webpage. This also gives the flexibility to define some keywords to implement a filter on the considered pages, max_depth, and timeout.
=> RecURLsive parser

plugins.json
Smitty Cat is a plugin designed for Cheshire-Cat, enhancing its capabilities with tracking features in LangSmith.
=> Add Smitty Cat plugin

plugins.json
https://github.com/pazoff/medical-cat
The plugin allows users to submit patient examination information through a form, which is then stored in text files. Additionally, the plugin provides functionalities to retrieve diagnosis reports and treatment plans for patients based on the submitted information.
=> add Medical Cat plugin

plugins.json
This plugin allows to set a list of filters and extract only the text in a specific list of tags
=> Introduced HTML parser

plugins.json
Added OctoCat plugin to plugins.json. This plugin is aimed to provide a natural language interface to OctoPrint servers. Hope you like it!
=> Add OctoCat plugin

plugins.json
Dynamic-Language is a  plugin to change the Language of the chatbot dynamically via web socket
=> Add Dynamic-Language 

plugins.json
Added Matryoshka Embeddings Integration
=> Matryoshka Embeddings

plugins.json
I added the experimental semantic chunker plugin
=> Semantic Chunking

plugins.json
https://github.com/pazoff/Piper-Cat
A plugin that makes possible the Cheshire Cat to be able to speak using offline Piper engine TTS.
=> add Piper Cat plugin

plugins.json
This plugin created by @dejan94it allows the Cheshire Cat to use tools written in R language (and to run R code, in general).
=> Update plugins with cc_Rtools

plugins.json
I've created a plugin to search duckduckgo for websites and scrape its results for detailed answers, I'm trying to add it to the plugins inventory :) 
I've tested the plugin locally, I've added a readme, a setting panel and a thumbnail.
=> adding duckcatgo plugin

plugins.json
This Cheshire Cat AI plugin hooks in to the conversation workflow between Cheshire Cat and the User keeping a log of the ongoing conversation.
The log can be analyzed later on to fine tune the Knowledge Base of Cheshire Cat AI.
This plugin is intended as an inspection tool. Please check for any legal compliance in your organization, for any privacy constraint on tracking an user conversation (i.e.: if the  user intentionally or unintentionally shares any sensitive information with the bot it will be feed in the Log for the conversation)
=> New plugin Cheshire Cat AI Conversation Logger

plugins.json
Added Delete docs with metadata filter
=> Added Delete docs with metadata filter

plugins.json
I added an integration for aleph alpha embedders
=> added aleph alpha integration

plugins.json
simple plugin that take as input an image containing math formulas and outputs the associated Latex code to render it.
=> detect math formulas from images and reproduce them in Latex syntax

plugins.json
Added the White Rabbit In Action plugin to enable `@white_rabbit_tool` annotation and schedule tool execution without writing specific code. 
No core changes were made, just some tricks to override traditional `@tool` annotation.
Let's break some stuff !!! 🚀
=> Added White Rabbit In Action plugin

plugins.json
Plugin for regolo.ai integration
=> Add regolo.ai plugin

plugins.json
Introducing the Cheshire Cat AI `dot commands` plugin, a handy utility designed to simplify and speed up your plugin development process. This tool allows you to interact with the Cat internals directly through chat commands. No need to switch contexts or break your workflow—just type commands starting with a dot (.) to perform various actions.
=> Dot Commands

plugins.json
Added Catcloak plugin to plugins.json
Catcloak is a plugin to enable Keycloak authentication with the new auth handlers interface.
Hope somebody will find it useful!
=> Added Catcloak plugin to plugins.json

plugins.json
Catnesina is a virtual assistant designed to support travellers by providing essential and up-to-date information on security, safety and health risks for international destinations. 
Powered by the data from “Viaggiare Sicuri” portal of the Italian Ministry of Foreign Affairs, this assistant offers quick answers to travellers’ questions regarding safety and security advisories, health headsup, and travel requirements.
This assistant is particularly valuable for Italian citizens planning to travel abroad, providing them with relevant and accurate guidance to make informed decisions. However, it may also accommodates travellers from other countries, offering reliable and universally applicable information to suit a wide range of travel needs.
By delivering real-time information directly …
=> Add catnesina plugin

plugins.json
I built a simple plugin that, given a sitemap URL, fetch its content and add each URL in the declarative memory
=> Sitemap Crawler

plugins.json
New plugin to add support to Voyage AI embeddingsss
=> Added Voyage AI plugin

plugins.json
Plugin for ask the Cat to search in internet informations and write citations in response text
=> Add miaotore plugin

plugins.json
Ingest all file in the directory as plain text
=> Add "Folder Ingestor" plugin

plugins.json
this plugin will add Petals LLM Settings.
=> add Cat on a Petals plugin

plugins.json
analyzes publicly traded companies using Warren Buffett’s value investing principles
More details are here:
https://github.com/silv3ri0/value_analysis/blob/main/README.md
=> Add Value investors analysis plugin

plugins.json
A plugin that makes possible the Cheshire Cat to be able to speak using offline Kokoro-FastAPI TTS.
- [https://github.com/pazoff/Kokoro-Cat](https://github.com/pazoff/Kokoro-Cat)
- [https://github.com/remsky/Kokoro-FastAPI](https://github.com/remsky/Kokoro-FastAPI)
=> add Kokoro Cat plugin

plugins.json
Filtered document search for the current user. It adds the user ID to the documents and filters the search to query only the documents of the current user.
=> Filtered Document Search

plugins.json
a plugin to play the cat's messages with voices from Eleven labs API
=> Added 'Voices' plugin

plugins.json
This PR adds a new plugin that enables the Cheshire Cat AI platform to send messages to Telegram users or groups. The plugin allows seamless integration with Telegram's messaging system, providing a convenient way for the AI to send notifications or updates to users through Telegram.
- Ability to send messages to multiple Telegram chat IDs simultaneously
- Support for SOCKS5 proxy for connections in restricted networks
- Configurable Telegram API server URL
- Complete documentation with setup instructions
- Implements asynchronous message sending to improve performance
- Uses aiohttp and aiohttp_socks for efficient HTTP requests
- Robust error handling for connection issues and invalid configurations
- Fully compatible with the Cheshire Cat plugin system
- Tested message sending to …
=> Added Telegram Message Sender Plugin

plugins.json
Added https://github.com/asterbini/UnstructuredCat  to parse many document types with a locally installed unstructured lib
=> Added UnstructuredCat to parse many documents types

plugins.json
Add plugin to extract and translate PDF content (including images) into rabbit_hole
=> Add vision pdf parser plugin

plugins.json
A Cheshire Cat plugin for seamless multi-chat management. It features automatic conversation naming, full create/delete/rename support, and includes a companion Gradio UI for an easy-to-use experience: https://github.com/net7/simple-multi-chat-ui
=> Simple Multi Chat plugin

plugins.json
A powerful security and moderation plugin that acts as a firewall for user prompts. It protects your Cheshire Cat instance from spam, abuse, and malicious inputs through rate limiting, content analysis (prompt length, forbidden keywords, complexity), and a progressive suspension system.
=> New Rate Limiter plugin by Net7
